sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'stable'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
